# This file is part of Harden Role
# Copyright (C) 2014 Bill Carlson
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
- name: "CCE-27002-5: accounts_password_minlen_login_defs"
  lineinfile:
    dest=/etc/login.defs
    line='PASS_MIN_LEN 14'
    regexp='^PASS_MIN_LEN'

- name: "CCE-27013-2: accounts_minimum_age_login_defs"
  lineinfile:
    dest=/etc/login.defs
    line='PASS_MIN_DAYS 1'
    regexp='PASS_MIN_DAYS'

- name: "CCE-26985-2: accounts_maximum_age_login_defs"
  lineinfile:
    dest=/etc/login.defs
    line='PASS_MAX_DAYS 60'
    regexp='PASS_MAX_DAYS'

- name: "CCE-27283-1: account_disable_post_pw_expiration"
  lineinfile:
    dest=/etc/default/useradd
    line='INACTIVE=35'
    regexp='INACTIVE'

- name: "CCE-27034-8: accounts_umask_cshrc"
  lineinfile:
    dest=/etc/csh.cshrc
    line="       umask 077"
    regexp='^ *umask *(002|077)'
    backup=yes

- name: "CCE-26669-2: accounts_umask_etc_profile"
  lineinfile:
    dest=/etc/profile
    line="       umask 077"
    regexp='^ *umask *(002|077)'
    backup=yes

- name: "CCE-26917-5: accounts_umask_bashrc"
  lineinfile:
    dest=/etc/bashrc
    line="       umask 077"
    regexp='^ *umask *(002|077)'
    backup=yes
